spring.application.name=SS8911

# server port
server.port=8911

# Automatic Restart
spring.devtools.restart.enabled=true

# Live Reload ?? ???
spring.devtools.livereload.enabled=true

# mariaDB
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://192.168.1.221:3306/SS8911
spring.datasource.username=ss8911
spring.datasource.password=1234

# jpa
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

logging.level.org.hibernate.type.descriptor.sql=trace

spring.thymeleaf.cache=false



spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=250MB

# ?? application.properties(?? .yml)? ?????
groq.api.key=${GROQ_API_KEY}
groq.api.url=https://api.groq.com/openai/v1/chat/completions
groq.model=llama-3.3-70b-versatile

cloudinary.cloud-name=ukmug4fv
cloudinary.api-key=625815843784595
cloudinary.api-secret=jlqYnhdSwkIpgeZFqEJSYBvEp0M

# ?? ??? SMS ?? ?? ??
# ?? API Key? ????? (????? ? ??? ??? ??? ?)
octomo.api-key=1f8c972c1e5e961f7d35eaddbc37995c28b470e38e4662b27e832b7b3deaadca
octomo.target-number=1666-3538

#toss
toss.payments.client-key=test_gck_GePWvyJnrKaQ9AePD9ab3gLzN97E
toss.payments.secret-key=test_gsk_6bJXmgo28eDZGwzz1Lv6rLAnGKWx
toss.payments.confirm-url=https://api.tosspayments.com/v1/payments/confirm
